# Generated by Django 4.1.3 on 2022-11-15 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('idhotel', models.AutoField(primary_key=True, serialize=False, verbose_name='idHotel')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('numeroplazas', models.IntegerField(verbose_name='Número de plazas')),
                ('codigopostal', models.CharField(max_length=5, verbose_name='Código postal')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('colonia', models.CharField(max_length=100, verbose_name='Colonia')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('estatus', models.BooleanField(default=True, verbose_name='Estatus')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('idsucursal', models.AutoField(primary_key=True, serialize=False, verbose_name='idSucursal')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('numeroplazas', models.IntegerField(verbose_name='Número de plazas')),
                ('codigopostal', models.CharField(max_length=5, verbose_name='Código postal')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('colonia', models.CharField(max_length=100, verbose_name='Colonia')),
                ('estatus', models.BooleanField(default=True, verbose_name='Estatus')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('idvuelo', models.AutoField(primary_key=True, serialize=False, verbose_name='idVuelo')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('numeroplazas', models.IntegerField(verbose_name='Número de plazas')),
                ('ciudadOrigen', models.CharField(max_length=100, verbose_name='Ciudad de Origen')),
                ('estadoOrigen', models.CharField(max_length=100, verbose_name='Estado de Origen')),
                ('paisOrigen', models.CharField(max_length=100, verbose_name='País de Origen')),
                ('ciudadDestino', models.CharField(max_length=100, verbose_name='Ciudad de Destino')),
                ('estadoDestino', models.CharField(max_length=100, verbose_name='Estado de Destino')),
                ('paisDestino', models.CharField(max_length=100, verbose_name='País de Destino')),
                ('estatus', models.BooleanField(default=True, verbose_name='Estatus')),
            ],
        ),
        migrations.CreateModel(
            name='Turista',
            fields=[
                ('idturista', models.AutoField(primary_key=True, serialize=False, verbose_name='idTurista')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidoM', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('apellidoP', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('codigopostal', models.CharField(max_length=5, verbose_name='Código Postal')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('colonia', models.CharField(max_length=100, verbose_name='Colonia')),
                ('regimen', models.CharField(max_length=50, verbose_name='Regimen')),
                ('claseTurista', models.CharField(max_length=50, verbose_name='Clase del Vuelo')),
                ('estatus', models.BooleanField(default=True, verbose_name='Estatus')),
                ('idhotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.hotel', verbose_name='idHotel')),
                ('idsucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.sucursal', verbose_name='idSucursal')),
                ('idvuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.vuelo', verbose_name='idVuelo')),
            ],
        ),
    ]
